# Generated by Django 3.0.8 on 2020-07-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='isilon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('folder_name', models.CharField(max_length=100)),
                ('folder_dir', models.TextField()),
                ('total_space', models.CharField(max_length=100)),
                ('used_space', models.CharField(max_length=100)),
                ('free_space', models.CharField(max_length=100)),
                ('percentage', models.CharField(max_length=100)),
                ('scan_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='radar05',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('folder_name', models.CharField(max_length=100)),
                ('folder_dir', models.TextField()),
                ('folder_size', models.BigIntegerField()),
                ('scan_date', models.DateTimeField()),
                ('time_duration', models.FloatField()),
            ],
        ),
    ]
