# Generated by Django 3.0.8 on 2020-07-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowSpace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='radar05_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('folder_name', models.CharField(max_length=100)),
                ('folder_dir', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('number', models.BigIntegerField()),
                ('size', models.BigIntegerField()),
                ('scan_date', models.DateTimeField()),
            ],
        ),
    ]
